package com.auzmor.netty.netty_httpserver.message;



// Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: routeguide.proto

public final class MessageProto {
 private MessageProto() {}
 public static void registerAllExtensions(
     com.google.protobuf.ExtensionRegistryLite registry) {
 }

 public static void registerAllExtensions(
     com.google.protobuf.ExtensionRegistry registry) {
   registerAllExtensions(
       (com.google.protobuf.ExtensionRegistryLite) registry);
 }
 public interface MessageOrBuilder extends
     // @@protoc_insertion_point(interface_extends:Message)
     com.google.protobuf.MessageOrBuilder {

   /**
    * <code>map&lt;string, string&gt; header = 1;</code>
    */
   int getHeaderCount();
   /**
    * <code>map&lt;string, string&gt; header = 1;</code>
    */
   boolean containsHeader(
       java.lang.String key);
   /**
    * Use {@link #getHeaderMap()} instead.
    */
   @java.lang.Deprecated
   java.util.Map<java.lang.String, java.lang.String>
   getHeader();
   /**
    * <code>map&lt;string, string&gt; header = 1;</code>
    */
   java.util.Map<java.lang.String, java.lang.String>
   getHeaderMap();
   /**
    * <code>map&lt;string, string&gt; header = 1;</code>
    */

   java.lang.String getHeaderOrDefault(
       java.lang.String key,
       java.lang.String defaultValue);
   /**
    * <code>map&lt;string, string&gt; header = 1;</code>
    */

   java.lang.String getHeaderOrThrow(
       java.lang.String key);

   /**
    * <code>map&lt;string, string&gt; query = 2;</code>
    */
   int getQueryCount();
   /**
    * <code>map&lt;string, string&gt; query = 2;</code>
    */
   boolean containsQuery(
       java.lang.String key);
   /**
    * Use {@link #getQueryMap()} instead.
    */
   @java.lang.Deprecated
   java.util.Map<java.lang.String, java.lang.String>
   getQuery();
   /**
    * <code>map&lt;string, string&gt; query = 2;</code>
    */
   java.util.Map<java.lang.String, java.lang.String>
   getQueryMap();
   /**
    * <code>map&lt;string, string&gt; query = 2;</code>
    */

   java.lang.String getQueryOrDefault(
       java.lang.String key,
       java.lang.String defaultValue);
   /**
    * <code>map&lt;string, string&gt; query = 2;</code>
    */

   java.lang.String getQueryOrThrow(
       java.lang.String key);
 }
 /**
  * Protobuf type {@code Message}
  */
 public  static final class Message extends
     com.google.protobuf.GeneratedMessageV3 implements
     // @@protoc_insertion_point(message_implements:Message)
     MessageOrBuilder {
   // Use Message.newBuilder() to construct.
   private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
     super(builder);
   }
   private Message() {
   }

   @java.lang.Override
   public final com.google.protobuf.UnknownFieldSet
   getUnknownFields() {
     return this.unknownFields;
   }
   private Message(
       com.google.protobuf.CodedInputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws com.google.protobuf.InvalidProtocolBufferException {
     this();
     int mutable_bitField0_ = 0;
     com.google.protobuf.UnknownFieldSet.Builder unknownFields =
         com.google.protobuf.UnknownFieldSet.newBuilder();
     try {
       boolean done = false;
       while (!done) {
         int tag = input.readTag();
         switch (tag) {
           case 0:
             done = true;
             break;
           default: {
             if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
               done = true;
             }
             break;
           }
           case 10: {
             if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
               header_ = com.google.protobuf.MapField.newMapField(
                   HeaderDefaultEntryHolder.defaultEntry);
               mutable_bitField0_ |= 0x00000001;
             }
             com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
             header__ = input.readMessage(
                 HeaderDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
             header_.getMutableMap().put(
                 header__.getKey(), header__.getValue());
             break;
           }
           case 18: {
             if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
               query_ = com.google.protobuf.MapField.newMapField(
                   QueryDefaultEntryHolder.defaultEntry);
               mutable_bitField0_ |= 0x00000002;
             }
             com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
             query__ = input.readMessage(
                 QueryDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
             query_.getMutableMap().put(
                 query__.getKey(), query__.getValue());
             break;
           }
         }
       }
     } catch (com.google.protobuf.InvalidProtocolBufferException e) {
       throw e.setUnfinishedMessage(this);
     } catch (java.io.IOException e) {
       throw new com.google.protobuf.InvalidProtocolBufferException(
           e).setUnfinishedMessage(this);
     } finally {
       this.unknownFields = unknownFields.build();
       makeExtensionsImmutable();
     }
   }
   public static final com.google.protobuf.Descriptors.Descriptor
       getDescriptor() {
     return MessageProto.internal_static_Message_descriptor;
   }

   @SuppressWarnings({"rawtypes"})
   protected com.google.protobuf.MapField internalGetMapField(
       int number) {
     switch (number) {
       case 1:
         return internalGetHeader();
       case 2:
         return internalGetQuery();
       default:
         throw new RuntimeException(
             "Invalid map field number: " + number);
     }
   }
   protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
       internalGetFieldAccessorTable() {
     return MessageProto.internal_static_Message_fieldAccessorTable
         .ensureFieldAccessorsInitialized(
             MessageProto.Message.class, MessageProto.Message.Builder.class);
   }

   public static final int HEADER_FIELD_NUMBER = 1;
   private static final class HeaderDefaultEntryHolder {
     static final com.google.protobuf.MapEntry<
         java.lang.String, java.lang.String> defaultEntry =
             com.google.protobuf.MapEntry
             .<java.lang.String, java.lang.String>newDefaultInstance(
                 MessageProto.internal_static_Message_HeaderEntry_descriptor, 
                 com.google.protobuf.WireFormat.FieldType.STRING,
                 "",
                 com.google.protobuf.WireFormat.FieldType.STRING,
                 "");
   }
   private com.google.protobuf.MapField<
       java.lang.String, java.lang.String> header_;
   private com.google.protobuf.MapField<java.lang.String, java.lang.String>
   internalGetHeader() {
     if (header_ == null) {
       return com.google.protobuf.MapField.emptyMapField(
           HeaderDefaultEntryHolder.defaultEntry);
     }
     return header_;
   }

   public int getHeaderCount() {
     return internalGetHeader().getMap().size();
   }
   /**
    * <code>map&lt;string, string&gt; header = 1;</code>
    */

   public boolean containsHeader(
       java.lang.String key) {
     if (key == null) { throw new java.lang.NullPointerException(); }
     return internalGetHeader().getMap().containsKey(key);
   }
   /**
    * Use {@link #getHeaderMap()} instead.
    */
   @java.lang.Deprecated
   public java.util.Map<java.lang.String, java.lang.String> getHeader() {
     return getHeaderMap();
   }
   /**
    * <code>map&lt;string, string&gt; header = 1;</code>
    */

   public java.util.Map<java.lang.String, java.lang.String> getHeaderMap() {
     return internalGetHeader().getMap();
   }
   /**
    * <code>map&lt;string, string&gt; header = 1;</code>
    */

   public java.lang.String getHeaderOrDefault(
       java.lang.String key,
       java.lang.String defaultValue) {
     if (key == null) { throw new java.lang.NullPointerException(); }
     java.util.Map<java.lang.String, java.lang.String> map =
         internalGetHeader().getMap();
     return map.containsKey(key) ? map.get(key) : defaultValue;
   }
   /**
    * <code>map&lt;string, string&gt; header = 1;</code>
    */

   public java.lang.String getHeaderOrThrow(
       java.lang.String key) {
     if (key == null) { throw new java.lang.NullPointerException(); }
     java.util.Map<java.lang.String, java.lang.String> map =
         internalGetHeader().getMap();
     if (!map.containsKey(key)) {
       throw new java.lang.IllegalArgumentException();
     }
     return map.get(key);
   }

   public static final int QUERY_FIELD_NUMBER = 2;
   private static final class QueryDefaultEntryHolder {
     static final com.google.protobuf.MapEntry<
         java.lang.String, java.lang.String> defaultEntry =
             com.google.protobuf.MapEntry
             .<java.lang.String, java.lang.String>newDefaultInstance(
                 MessageProto.internal_static_Message_QueryEntry_descriptor, 
                 com.google.protobuf.WireFormat.FieldType.STRING,
                 "",
                 com.google.protobuf.WireFormat.FieldType.STRING,
                 "");
   }
   private com.google.protobuf.MapField<
       java.lang.String, java.lang.String> query_;
   private com.google.protobuf.MapField<java.lang.String, java.lang.String>
   internalGetQuery() {
     if (query_ == null) {
       return com.google.protobuf.MapField.emptyMapField(
           QueryDefaultEntryHolder.defaultEntry);
     }
     return query_;
   }

   public int getQueryCount() {
     return internalGetQuery().getMap().size();
   }
   /**
    * <code>map&lt;string, string&gt; query = 2;</code>
    */

   public boolean containsQuery(
       java.lang.String key) {
     if (key == null) { throw new java.lang.NullPointerException(); }
     return internalGetQuery().getMap().containsKey(key);
   }
   /**
    * Use {@link #getQueryMap()} instead.
    */
   @java.lang.Deprecated
   public java.util.Map<java.lang.String, java.lang.String> getQuery() {
     return getQueryMap();
   }
   /**
    * <code>map&lt;string, string&gt; query = 2;</code>
    */

   public java.util.Map<java.lang.String, java.lang.String> getQueryMap() {
     return internalGetQuery().getMap();
   }
   /**
    * <code>map&lt;string, string&gt; query = 2;</code>
    */

   public java.lang.String getQueryOrDefault(
       java.lang.String key,
       java.lang.String defaultValue) {
     if (key == null) { throw new java.lang.NullPointerException(); }
     java.util.Map<java.lang.String, java.lang.String> map =
         internalGetQuery().getMap();
     return map.containsKey(key) ? map.get(key) : defaultValue;
   }
   /**
    * <code>map&lt;string, string&gt; query = 2;</code>
    */

   public java.lang.String getQueryOrThrow(
       java.lang.String key) {
     if (key == null) { throw new java.lang.NullPointerException(); }
     java.util.Map<java.lang.String, java.lang.String> map =
         internalGetQuery().getMap();
     if (!map.containsKey(key)) {
       throw new java.lang.IllegalArgumentException();
     }
     return map.get(key);
   }

   private byte memoizedIsInitialized = -1;
   public final boolean isInitialized() {
     byte isInitialized = memoizedIsInitialized;
     if (isInitialized == 1) return true;
     if (isInitialized == 0) return false;

     memoizedIsInitialized = 1;
     return true;
   }

   public void writeTo(com.google.protobuf.CodedOutputStream output)
                       throws java.io.IOException {
     com.google.protobuf.GeneratedMessageV3
       .serializeStringMapTo(
         output,
         internalGetHeader(),
         HeaderDefaultEntryHolder.defaultEntry,
         1);
     com.google.protobuf.GeneratedMessageV3
       .serializeStringMapTo(
         output,
         internalGetQuery(),
         QueryDefaultEntryHolder.defaultEntry,
         2);
     unknownFields.writeTo(output);
   }

   public int getSerializedSize() {
     int size = memoizedSize;
     if (size != -1) return size;

     size = 0;
     for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
          : internalGetHeader().getMap().entrySet()) {
       com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
       header__ = HeaderDefaultEntryHolder.defaultEntry.newBuilderForType()
           .setKey(entry.getKey())
           .setValue(entry.getValue())
           .build();
       size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(1, header__);
     }
     for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
          : internalGetQuery().getMap().entrySet()) {
       com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
       query__ = QueryDefaultEntryHolder.defaultEntry.newBuilderForType()
           .setKey(entry.getKey())
           .setValue(entry.getValue())
           .build();
       size += com.google.protobuf.CodedOutputStream
           .computeMessageSize(2, query__);
     }
     size += unknownFields.getSerializedSize();
     memoizedSize = size;
     return size;
   }

   private static final long serialVersionUID = 0L;
   @java.lang.Override
   public boolean equals(final java.lang.Object obj) {
     if (obj == this) {
      return true;
     }
     if (!(obj instanceof MessageProto.Message)) {
       return super.equals(obj);
     }
     MessageProto.Message other = (MessageProto.Message) obj;

     boolean result = true;
     result = result && internalGetHeader().equals(
         other.internalGetHeader());
     result = result && internalGetQuery().equals(
         other.internalGetQuery());
     result = result && unknownFields.equals(other.unknownFields);
     return result;
   }

   @java.lang.Override
   public int hashCode() {
     if (memoizedHashCode != 0) {
       return memoizedHashCode;
     }
     int hash = 41;
     hash = (19 * hash) + getDescriptor().hashCode();
     if (!internalGetHeader().getMap().isEmpty()) {
       hash = (37 * hash) + HEADER_FIELD_NUMBER;
       hash = (53 * hash) + internalGetHeader().hashCode();
     }
     if (!internalGetQuery().getMap().isEmpty()) {
       hash = (37 * hash) + QUERY_FIELD_NUMBER;
       hash = (53 * hash) + internalGetQuery().hashCode();
     }
     hash = (29 * hash) + unknownFields.hashCode();
     memoizedHashCode = hash;
     return hash;
   }

   public static MessageProto.Message parseFrom(
       java.nio.ByteBuffer data)
       throws com.google.protobuf.InvalidProtocolBufferException {
     return PARSER.parseFrom(data);
   }
   public static MessageProto.Message parseFrom(
       java.nio.ByteBuffer data,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws com.google.protobuf.InvalidProtocolBufferException {
     return PARSER.parseFrom(data, extensionRegistry);
   }
   public static MessageProto.Message parseFrom(
       com.google.protobuf.ByteString data)
       throws com.google.protobuf.InvalidProtocolBufferException {
     return PARSER.parseFrom(data);
   }
   public static MessageProto.Message parseFrom(
       com.google.protobuf.ByteString data,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws com.google.protobuf.InvalidProtocolBufferException {
     return PARSER.parseFrom(data, extensionRegistry);
   }
   public static MessageProto.Message parseFrom(byte[] data)
       throws com.google.protobuf.InvalidProtocolBufferException {
     return PARSER.parseFrom(data);
   }
   public static MessageProto.Message parseFrom(
       byte[] data,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws com.google.protobuf.InvalidProtocolBufferException {
     return PARSER.parseFrom(data, extensionRegistry);
   }
   public static MessageProto.Message parseFrom(java.io.InputStream input)
       throws java.io.IOException {
     return com.google.protobuf.GeneratedMessageV3
         .parseWithIOException(PARSER, input);
   }
   public static MessageProto.Message parseFrom(
       java.io.InputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws java.io.IOException {
     return com.google.protobuf.GeneratedMessageV3
         .parseWithIOException(PARSER, input, extensionRegistry);
   }
   public static MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
       throws java.io.IOException {
     return com.google.protobuf.GeneratedMessageV3
         .parseDelimitedWithIOException(PARSER, input);
   }
   public static MessageProto.Message parseDelimitedFrom(
       java.io.InputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws java.io.IOException {
     return com.google.protobuf.GeneratedMessageV3
         .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
   }
   public static MessageProto.Message parseFrom(
       com.google.protobuf.CodedInputStream input)
       throws java.io.IOException {
     return com.google.protobuf.GeneratedMessageV3
         .parseWithIOException(PARSER, input);
   }
   public static MessageProto.Message parseFrom(
       com.google.protobuf.CodedInputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws java.io.IOException {
     return com.google.protobuf.GeneratedMessageV3
         .parseWithIOException(PARSER, input, extensionRegistry);
   }

   public Builder newBuilderForType() { return newBuilder(); }
   public static Builder newBuilder() {
     return DEFAULT_INSTANCE.toBuilder();
   }
   public static Builder newBuilder(MessageProto.Message prototype) {
     return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
   }
   public Builder toBuilder() {
     return this == DEFAULT_INSTANCE
         ? new Builder() : new Builder().mergeFrom(this);
   }

   @java.lang.Override
   protected Builder newBuilderForType(
       com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
     Builder builder = new Builder(parent);
     return builder;
   }
   /**
    * Protobuf type {@code Message}
    */
   public static final class Builder extends
       com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
       // @@protoc_insertion_point(builder_implements:Message)
       MessageProto.MessageOrBuilder {
     public static final com.google.protobuf.Descriptors.Descriptor
         getDescriptor() {
       return MessageProto.internal_static_Message_descriptor;
     }

     @SuppressWarnings({"rawtypes"})
     protected com.google.protobuf.MapField internalGetMapField(
         int number) {
       switch (number) {
         case 1:
           return internalGetHeader();
         case 2:
           return internalGetQuery();
         default:
           throw new RuntimeException(
               "Invalid map field number: " + number);
       }
     }
     @SuppressWarnings({"rawtypes"})
     protected com.google.protobuf.MapField internalGetMutableMapField(
         int number) {
       switch (number) {
         case 1:
           return internalGetMutableHeader();
         case 2:
           return internalGetMutableQuery();
         default:
           throw new RuntimeException(
               "Invalid map field number: " + number);
       }
     }
     protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
         internalGetFieldAccessorTable() {
       return MessageProto.internal_static_Message_fieldAccessorTable
           .ensureFieldAccessorsInitialized(
               MessageProto.Message.class, MessageProto.Message.Builder.class);
     }

     // Construct using MessageProto.Message.newBuilder()
     private Builder() {
       maybeForceBuilderInitialization();
     }

     private Builder(
         com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
       super(parent);
       maybeForceBuilderInitialization();
     }
     private void maybeForceBuilderInitialization() {
       if (com.google.protobuf.GeneratedMessageV3
               .alwaysUseFieldBuilders) {
       }
     }
     public Builder clear() {
       super.clear();
       internalGetMutableHeader().clear();
       internalGetMutableQuery().clear();
       return this;
     }

     public com.google.protobuf.Descriptors.Descriptor
         getDescriptorForType() {
       return MessageProto.internal_static_Message_descriptor;
     }

     public MessageProto.Message getDefaultInstanceForType() {
       return MessageProto.Message.getDefaultInstance();
     }

     public MessageProto.Message build() {
       MessageProto.Message result = buildPartial();
       if (!result.isInitialized()) {
         throw newUninitializedMessageException(result);
       }
       return result;
     }

     public MessageProto.Message buildPartial() {
       MessageProto.Message result = new MessageProto.Message(this);
       int from_bitField0_ = bitField0_;
       result.header_ = internalGetHeader();
       result.header_.makeImmutable();
       result.query_ = internalGetQuery();
       result.query_.makeImmutable();
       onBuilt();
       return result;
     }

     public Builder clone() {
       return (Builder) super.clone();
     }
     public Builder setField(
         com.google.protobuf.Descriptors.FieldDescriptor field,
         Object value) {
       return (Builder) super.setField(field, value);
     }
     public Builder clearField(
         com.google.protobuf.Descriptors.FieldDescriptor field) {
       return (Builder) super.clearField(field);
     }
     public Builder clearOneof(
         com.google.protobuf.Descriptors.OneofDescriptor oneof) {
       return (Builder) super.clearOneof(oneof);
     }
     public Builder setRepeatedField(
         com.google.protobuf.Descriptors.FieldDescriptor field,
         int index, Object value) {
       return (Builder) super.setRepeatedField(field, index, value);
     }
     public Builder addRepeatedField(
         com.google.protobuf.Descriptors.FieldDescriptor field,
         Object value) {
       return (Builder) super.addRepeatedField(field, value);
     }
     public Builder mergeFrom(com.google.protobuf.Message other) {
       if (other instanceof MessageProto.Message) {
         return mergeFrom((MessageProto.Message)other);
       } else {
         super.mergeFrom(other);
         return this;
       }
     }

     public Builder mergeFrom(MessageProto.Message other) {
       if (other == MessageProto.Message.getDefaultInstance()) return this;
       internalGetMutableHeader().mergeFrom(
           other.internalGetHeader());
       internalGetMutableQuery().mergeFrom(
           other.internalGetQuery());
       this.mergeUnknownFields(other.unknownFields);
       onChanged();
       return this;
     }

     public final boolean isInitialized() {
       return true;
     }

     public Builder mergeFrom(
         com.google.protobuf.CodedInputStream input,
         com.google.protobuf.ExtensionRegistryLite extensionRegistry)
         throws java.io.IOException {
       MessageProto.Message parsedMessage = null;
       try {
         parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
       } catch (com.google.protobuf.InvalidProtocolBufferException e) {
         parsedMessage = (MessageProto.Message) e.getUnfinishedMessage();
         throw e.unwrapIOException();
       } finally {
         if (parsedMessage != null) {
           mergeFrom(parsedMessage);
         }
       }
       return this;
     }
     private int bitField0_;

     private com.google.protobuf.MapField<
         java.lang.String, java.lang.String> header_;
     private com.google.protobuf.MapField<java.lang.String, java.lang.String>
     internalGetHeader() {
       if (header_ == null) {
         return com.google.protobuf.MapField.emptyMapField(
             HeaderDefaultEntryHolder.defaultEntry);
       }
       return header_;
     }
     private com.google.protobuf.MapField<java.lang.String, java.lang.String>
     internalGetMutableHeader() {
       onChanged();;
       if (header_ == null) {
         header_ = com.google.protobuf.MapField.newMapField(
             HeaderDefaultEntryHolder.defaultEntry);
       }
       if (!header_.isMutable()) {
         header_ = header_.copy();
       }
       return header_;
     }

     public int getHeaderCount() {
       return internalGetHeader().getMap().size();
     }
     /**
      * <code>map&lt;string, string&gt; header = 1;</code>
      */

     public boolean containsHeader(
         java.lang.String key) {
       if (key == null) { throw new java.lang.NullPointerException(); }
       return internalGetHeader().getMap().containsKey(key);
     }
     /**
      * Use {@link #getHeaderMap()} instead.
      */
     @java.lang.Deprecated
     public java.util.Map<java.lang.String, java.lang.String> getHeader() {
       return getHeaderMap();
     }
     /**
      * <code>map&lt;string, string&gt; header = 1;</code>
      */

     public java.util.Map<java.lang.String, java.lang.String> getHeaderMap() {
       return internalGetHeader().getMap();
     }
     /**
      * <code>map&lt;string, string&gt; header = 1;</code>
      */

     public java.lang.String getHeaderOrDefault(
         java.lang.String key,
         java.lang.String defaultValue) {
       if (key == null) { throw new java.lang.NullPointerException(); }
       java.util.Map<java.lang.String, java.lang.String> map =
           internalGetHeader().getMap();
       return map.containsKey(key) ? map.get(key) : defaultValue;
     }
     /**
      * <code>map&lt;string, string&gt; header = 1;</code>
      */

     public java.lang.String getHeaderOrThrow(
         java.lang.String key) {
       if (key == null) { throw new java.lang.NullPointerException(); }
       java.util.Map<java.lang.String, java.lang.String> map =
           internalGetHeader().getMap();
       if (!map.containsKey(key)) {
         throw new java.lang.IllegalArgumentException();
       }
       return map.get(key);
     }

     public Builder clearHeader() {
       internalGetMutableHeader().getMutableMap()
           .clear();
       return this;
     }
     /**
      * <code>map&lt;string, string&gt; header = 1;</code>
      */

     public Builder removeHeader(
         java.lang.String key) {
       if (key == null) { throw new java.lang.NullPointerException(); }
       internalGetMutableHeader().getMutableMap()
           .remove(key);
       return this;
     }
     /**
      * Use alternate mutation accessors instead.
      */
     @java.lang.Deprecated
     public java.util.Map<java.lang.String, java.lang.String>
     getMutableHeader() {
       return internalGetMutableHeader().getMutableMap();
     }
     /**
      * <code>map&lt;string, string&gt; header = 1;</code>
      */
     public Builder putHeader(
         java.lang.String key,
         java.lang.String value) {
       if (key == null) { throw new java.lang.NullPointerException(); }
       if (value == null) { throw new java.lang.NullPointerException(); }
       internalGetMutableHeader().getMutableMap()
           .put(key, value);
       return this;
     }
     /**
      * <code>map&lt;string, string&gt; header = 1;</code>
      */

     public Builder putAllHeader(
         java.util.Map<java.lang.String, java.lang.String> values) {
       internalGetMutableHeader().getMutableMap()
           .putAll(values);
       return this;
     }

     private com.google.protobuf.MapField<
         java.lang.String, java.lang.String> query_;
     private com.google.protobuf.MapField<java.lang.String, java.lang.String>
     internalGetQuery() {
       if (query_ == null) {
         return com.google.protobuf.MapField.emptyMapField(
             QueryDefaultEntryHolder.defaultEntry);
       }
       return query_;
     }
     private com.google.protobuf.MapField<java.lang.String, java.lang.String>
     internalGetMutableQuery() {
       onChanged();;
       if (query_ == null) {
         query_ = com.google.protobuf.MapField.newMapField(
             QueryDefaultEntryHolder.defaultEntry);
       }
       if (!query_.isMutable()) {
         query_ = query_.copy();
       }
       return query_;
     }

     public int getQueryCount() {
       return internalGetQuery().getMap().size();
     }
     /**
      * <code>map&lt;string, string&gt; query = 2;</code>
      */

     public boolean containsQuery(
         java.lang.String key) {
       if (key == null) { throw new java.lang.NullPointerException(); }
       return internalGetQuery().getMap().containsKey(key);
     }
     /**
      * Use {@link #getQueryMap()} instead.
      */
     @java.lang.Deprecated
     public java.util.Map<java.lang.String, java.lang.String> getQuery() {
       return getQueryMap();
     }
     /**
      * <code>map&lt;string, string&gt; query = 2;</code>
      */

     public java.util.Map<java.lang.String, java.lang.String> getQueryMap() {
       return internalGetQuery().getMap();
     }
     /**
      * <code>map&lt;string, string&gt; query = 2;</code>
      */

     public java.lang.String getQueryOrDefault(
         java.lang.String key,
         java.lang.String defaultValue) {
       if (key == null) { throw new java.lang.NullPointerException(); }
       java.util.Map<java.lang.String, java.lang.String> map =
           internalGetQuery().getMap();
       return map.containsKey(key) ? map.get(key) : defaultValue;
     }
     /**
      * <code>map&lt;string, string&gt; query = 2;</code>
      */

     public java.lang.String getQueryOrThrow(
         java.lang.String key) {
       if (key == null) { throw new java.lang.NullPointerException(); }
       java.util.Map<java.lang.String, java.lang.String> map =
           internalGetQuery().getMap();
       if (!map.containsKey(key)) {
         throw new java.lang.IllegalArgumentException();
       }
       return map.get(key);
     }

     public Builder clearQuery() {
       internalGetMutableQuery().getMutableMap()
           .clear();
       return this;
     }
     /**
      * <code>map&lt;string, string&gt; query = 2;</code>
      */

     public Builder removeQuery(
         java.lang.String key) {
       if (key == null) { throw new java.lang.NullPointerException(); }
       internalGetMutableQuery().getMutableMap()
           .remove(key);
       return this;
     }
     /**
      * Use alternate mutation accessors instead.
      */
     @java.lang.Deprecated
     public java.util.Map<java.lang.String, java.lang.String>
     getMutableQuery() {
       return internalGetMutableQuery().getMutableMap();
     }
     /**
      * <code>map&lt;string, string&gt; query = 2;</code>
      */
     public Builder putQuery(
         java.lang.String key,
         java.lang.String value) {
       if (key == null) { throw new java.lang.NullPointerException(); }
       if (value == null) { throw new java.lang.NullPointerException(); }
       internalGetMutableQuery().getMutableMap()
           .put(key, value);
       return this;
     }
     /**
      * <code>map&lt;string, string&gt; query = 2;</code>
      */

     public Builder putAllQuery(
         java.util.Map<java.lang.String, java.lang.String> values) {
       internalGetMutableQuery().getMutableMap()
           .putAll(values);
       return this;
     }
     public final Builder setUnknownFields(
         final com.google.protobuf.UnknownFieldSet unknownFields) {
       return super.setUnknownFields(unknownFields);
     }

     public final Builder mergeUnknownFields(
         final com.google.protobuf.UnknownFieldSet unknownFields) {
       return super.mergeUnknownFields(unknownFields);
     }


     // @@protoc_insertion_point(builder_scope:Message)
   }

   // @@protoc_insertion_point(class_scope:Message)
   private static final MessageProto.Message DEFAULT_INSTANCE;
   static {
     DEFAULT_INSTANCE = new MessageProto.Message();
   }

   public static MessageProto.Message getDefaultInstance() {
     return DEFAULT_INSTANCE;
   }

   @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
       PARSER = new com.google.protobuf.AbstractParser<Message>() {
     public Message parsePartialFrom(
         com.google.protobuf.CodedInputStream input,
         com.google.protobuf.ExtensionRegistryLite extensionRegistry)
         throws com.google.protobuf.InvalidProtocolBufferException {
         return new Message(input, extensionRegistry);
     }
   };

   public static com.google.protobuf.Parser<Message> parser() {
     return PARSER;
   }

   @java.lang.Override
   public com.google.protobuf.Parser<Message> getParserForType() {
     return PARSER;
   }

   public MessageProto.Message getDefaultInstanceForType() {
     return DEFAULT_INSTANCE;
   }

 }

 private static final com.google.protobuf.Descriptors.Descriptor
   internal_static_Message_descriptor;
 private static final 
   com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
     internal_static_Message_fieldAccessorTable;
 private static final com.google.protobuf.Descriptors.Descriptor
   internal_static_Message_HeaderEntry_descriptor;
 private static final 
   com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
     internal_static_Message_HeaderEntry_fieldAccessorTable;
 private static final com.google.protobuf.Descriptors.Descriptor
   internal_static_Message_QueryEntry_descriptor;
 private static final 
   com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
     internal_static_Message_QueryEntry_fieldAccessorTable;

 public static com.google.protobuf.Descriptors.FileDescriptor
     getDescriptor() {
   return descriptor;
 }
 private static  com.google.protobuf.Descriptors.FileDescriptor
     descriptor;
 static {
   java.lang.String[] descriptorData = {
     "\n\020routeguide.proto\"\260\001\n\007Message\022$\n\006header" +
     "\030\001 \003(\0132\024.Message.HeaderEntry\022\"\n\005query\030\002 " +
     "\003(\0132\023.Message.QueryEntry\032-\n\013HeaderEntry\022" +
     "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032,\n\nQuery" +
     "Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\016B" +
     "\014MessageProto"
   };
   com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
       new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
         public com.google.protobuf.ExtensionRegistry assignDescriptors(
             com.google.protobuf.Descriptors.FileDescriptor root) {
           descriptor = root;
           return null;
         }
       };
   com.google.protobuf.Descriptors.FileDescriptor
     .internalBuildGeneratedFileFrom(descriptorData,
       new com.google.protobuf.Descriptors.FileDescriptor[] {
       }, assigner);
   internal_static_Message_descriptor =
     getDescriptor().getMessageTypes().get(0);
   internal_static_Message_fieldAccessorTable = new
     com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
       internal_static_Message_descriptor,
       new java.lang.String[] { "Header", "Query", });
   internal_static_Message_HeaderEntry_descriptor =
     internal_static_Message_descriptor.getNestedTypes().get(0);
   internal_static_Message_HeaderEntry_fieldAccessorTable = new
     com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
       internal_static_Message_HeaderEntry_descriptor,
       new java.lang.String[] { "Key", "Value", });
   internal_static_Message_QueryEntry_descriptor =
     internal_static_Message_descriptor.getNestedTypes().get(1);
   internal_static_Message_QueryEntry_fieldAccessorTable = new
     com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
       internal_static_Message_QueryEntry_descriptor,
       new java.lang.String[] { "Key", "Value", });
 }

 // @@protoc_insertion_point(outer_class_scope)
}
